name: Makefile CI

on:
  workflow_dispatch:
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
      - 'build/*'
      - 'util/*'
  push:
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
      - 'build/*'
      - 'util/*'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
      - 'build/*'
      - 'util/*'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt install -y astyle cppcheck catch2 cmake 7zip

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: format_check
      working-directory: ./
      run: ./tools/format.sh --dry

    - name: Build native libraries
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_MOD_LIBRARIES=ON -DBUILD_MOD_PK3=OFF -DBUILD_MOD_QVMS=OFF -DBUILD_TESTS=OFF
        cmake --build build

    - name: Build qvm
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_MOD_LIBRARIES=OFF -DBUILD_MOD_PK3=ON -DBUILD_MOD_QVMS=ON -DBUILD_TESTS=OFF
        cmake --build build

    - name: Run tests
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_MOD_LIBRARIES=OFF -DBUILD_MOD_PK3=OFF -DBUILD_MOD_QVMS=OFF -DBUILD_TESTS=ON
        cmake --build build

    - uses: actions/upload-artifact@v4
      with:
        name: osp2_pk3
        path: build/Release/osp/*.pk3
        if-no-files-found: error
        retention-days: 5

    - uses: actions/upload-artifact@v4
      with:
        name: osp2_linux
        path: build/Release/osp/*.so
        if-no-files-found: error
        retention-days: 5

  mingw:
    name: MinGW GCC
    needs: linux 

    runs-on: windows-2022

    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build native libraries
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_MOD_LIBRARIES=ON -DBUILD_MOD_PK3=OFF -DBUILD_MOD_QVMS=OFF -DBUILD_TESTS=OFF
        cmake --build build

    - name: Build qvm
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_MOD_LIBRARIES=OFF -DBUILD_MOD_PK3=ON -DBUILD_MOD_QVMS=ON -DBUILD_TESTS=OFF
        cmake --build build

    - name: Run tests
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_MOD_LIBRARIES=OFF -DBUILD_MOD_PK3=OFF -DBUILD_MOD_QVMS=OFF -DBUILD_TESTS=ON
        cmake --build build

    - uses: actions/upload-artifact@v4
      with:
        name: osp2_windows
        path: build/Release/osp/*.dll
        if-no-files-found: error
        retention-days: 5

  create-latest:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [linux, mingw]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create latest build
        uses: czietz/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: Latest Build
          files: |
            osp2_windows
            osp2_linux
            osp2_pk3



